### ISSUE TITLE
Rename to Promise.sequential?

### ISSUE THREAD

**Issue by rauschma** [russiann/promise-sequencial#1]
The “c” in “sequencial” is a typo. Have you considered renaming the repo?

**Comment by russiann** [comment]
😅 Wow hehe, I'm Brazilian and I still have a little difficulty with english suffixes, unintentionally I wrote this word in Portuguese. I will fix this.

**Comment by russiann** [comment]
Fixed! 
(I know your blog, it is amazing! I'm your follower 😀 )

**Comment by rauschma** [comment]
Ah, nice to hear! Thanks for the fix!
