### ISSUE TITLE
Even if there is an error in the middle, it runs to the end

### ISSUE THREAD

**Issue by groge** [russiann/promise-sequencial#9]
I was expected stop loop if there is a error, but didn't.

    const sequential = require('promise-sequential');
    const array = [1,2,3,4,5,6,7];
    sequential(array.map((item) => {
        return function(previousResponse, responses, count) {
            return new Promise((resolve,reject) => {
                setTimeout(() => {
                    console.log("return ", item)
                    if( item < 4){
                        resolve(item)
                    }else{
                        reject(item)
                    }
                }, 100)
            })
        }
    }))
        .then(res => {
            console.log("[res]", res)
        })
        .catch(err => {
            console.log("[err]", err)
        })

result is...
return  1
return  2
return  3
return  4
[err] 4
return  5
return  6
return  7

but waterfall does

    const waterfall = require("promise-waterfall");
    const array = [1,2,3,4,5,6,7];
    waterfall(array.map((item) => {
        return function() {
            return new Promise((resolve,reject) => {
                //console.log("run ",item)
                setTimeout(() => {
                    console.log("return ", item)
                    if( item < 4){
                        resolve(item)
                    }else{
                        reject(item)
                    }
                }, 500)
            })
        }
    }))
        .then(res => {
            console.log("[res]", res)
        })
        .catch(err => {
            console.log("[err]", err)
        })

result is...

return  1
return  2
return  3
return  4
[err] 4

I wanna use previousResponse, responses, count variables....

Thanks

**Comment by Sigmus** [comment]
Have you ever tried http://reactivex.io/ ?

**Comment by Kaishiyoku** [comment]
Hi, I experienced the same. I really expected that the promise chain is being stopped when an error is being returned in between but it runs until the end.

**Comment by Floppy** [comment]
I will do a proper PR, but until I get to that, I've fixed this problem by changing the code to:

```
module.exports = (promises) => {
  if (!Array.isArray(promises)) {
    throw new Error('First argument need to be an array of Promises');
  }

  return new Promise((resolve, reject) => {
    let count = 0;
    let results = [];

    const iterateeFunc = (previousPromise, currentPromise) => previousPromise
      .then((result) => {
        if (count++ !== 0) results = results.concat(result);
        return currentPromise(result, results, count);
      });

    const allPromises = promises.concat(() => Promise.resolve());

    allPromises
      .reduce(iterateeFunc, Promise.resolve(false))
      .then(() => {
        resolve(results);
      })
      .catch((err) => {
        reject(err);
      });
  });
};
```

There's some eslint changes in there too - I'll keep my PR close to the original when I get to it, but I thought this might help in the meantime.

**Comment by AntonioRecaldeRusso** [comment]
I opened PR #11, fixing this problem and cleaning up the code a little bit.
If it is not merged right away, feel free to use `promise-sequential` from
https://github.com/DataSenseAnalytics/promise-sequential

**Comment by hjylewis** [comment]
@russiann since this was merged in can you publish the new code to npm?
